#include "Edge.h"
#include "FloatImage.h"
#include "GLine2D.h"
//#include "apriltags/GLineSegment2D.h"
#include "Gaussian.h"
//#include "apriltags/GrayModel.h"
//#include "apriltags/Gridder.h"
#include "Homography33.h"
#include "MathUtil.h"
//#include "apriltags/Quad.h"
//#include "apriltags/Segment.h"
//#include "apriltags/TagDetection.h"
//#include "apriltags/TagDetector.h"
//#include "apriltags/TagFamily.h"
#include "UnionFindSimple.h"
#include "XYWeight.h"

